### ISSUE TITLE
新規登録を開放していないサーバーを除外

### ISSUE THREAD

**Issue by CyberRex0** [joinmisskey/api#50]
お一人様など新規登録を開放していないサーバーもリストに追加されているため、joinmisskeyの目的も踏まえて開放していないサーバーを除外するのが望ましい。

**Comment by tamaina** [comment]
join.misskey.pageはデフォルトが開放のみにするようになっていたけどmisskey-hubはすべてがデフォルトになっているのか

（とりあえずこちらのapiで除外する予定はないです）
