### ISSUE TITLE
v12以降のサーバーしかリストに載らなくなっている

### ISSUE THREAD

**Issue by tkmrgit** [joinmisskey/api#52]
v10やv11系列のサーバーがサーバーリストに出てこなくなっています。
古い環境を利用しておりv10やv11サーバーの利用を求めているユーザーもいるためリスト一覧に掲載されるようにしてほしい。
なお旧バージョンでセキュリティ対応になっていないサーバーについては除外されていても問題は無いかなと思います

**Comment by tamaina** [comment]
こちらの方針となります。ご了承ください。

**Comment by tamaina** [comment]
（実際のところ、charts/notesのGETを実装してもらってこっちの原リストに戻せばいけるとは思いますが…）

**Comment by tkmrgit** [comment]
charts/notesのGET に対応して https://github.com/joinmisskey/api/commit/0180b7e5c6fdad7b2c3795169c5ee32de38df167 から除去されれば再度掲載可能でOK？

**Comment by tamaina** [comment]
多分そう
